openapi: 3.0.3
info:
  title: dockey api
  description: |-
    api docs for your favorite document collaborating app
  version: 1.0.0
servers:
  - url: http://74.242.214.25/v1/api
    description: Development server
tags:
  - name: users
    description: User-related operations
  - name: documents
    description: Document management operations
  - name: doc-groups
    description: Operations related to document groups
  - name: comments
    description: Operations about comments
paths:
  /users:
    get:
      tags:
        - users
      summary: Get all users
      description: Retrieve a list of all users
      operationId: getAllUsers
      responses:
        '200':
          description: List of users retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      tags:
        - users
      summary: Create a new user
      description: Create a new user in the system
      operationId: createUser
      requestBody:
        description: User object to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
  /users/register:
    post:
      tags:
        - users
      summary: Register a new user
      description: Register a new user with Keycloak and create profile
      operationId: registerUser
      requestBody:
        description: User registration details
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input or user already exists
  /users/login:
    post:
      tags:
        - users
      summary: Login user
      description: Authenticate user and return access token
      operationId: loginUser
      requestBody:
        description: User login credentials
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials
  /users/refresh:
    post:
      tags:
        - users
      summary: Refresh access token
      description: Get a new access token using refresh token
      operationId: refreshToken
      requestBody:
        description: Refresh token
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
      responses:
        '200':
          description: Token refreshed successfully
        '401':
          description: Invalid or expired refresh token
  /users/me:
    get:
      tags:
        - users
      summary: Get current user
      description: Get the profile of the currently logged-in user
      operationId: getCurrentUser
      responses:
        '200':
          description: Current user retrieved successfully
        '404':
          description: User profile not found
    delete:
      tags:
        - users
      summary: Delete current user account
      description: Delete the currently logged-in user's account
      operationId: deleteCurrentUser
      responses:
        '204':
          description: Account deleted successfully
        '401':
          description: Not authenticated
        '404':
          description: User not found
  /users/{id}:
    get:
      tags:
        - users
      summary: Get user by ID
      description: Retrieve a specific user by their ID
      operationId: getUser
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: User retrieved successfully
        '404':
          description: User not found
    put:
      tags:
        - users
      summary: Update a user
      description: Update an existing user
      operationId: updateUser
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Updated user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User updated successfully
        '404':
          description: User not found
    delete:
      tags:
        - users
      summary: Delete a user
      description: Delete a user by their ID
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: User deleted successfully
        '404':
          description: User not found
        '403':
          description: Forbidden - cannot delete other users
  /users/email/{email}:
    get:
      tags:
        - users
      summary: Get user by email
      description: Retrieve a user by their email address
      operationId: getUserByEmail
      parameters:
        - name: email
          in: path
          description: User email
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User retrieved successfully
        '404':
          description: User not found
  /documents:
    get:
      tags:
      - documents
      summary: Get all documents
      description: Retrieve a list of all documents
      operationId: getAllDocuments
      responses:
        '200':
          description: List of documents retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'
    post:
      tags:
      - documents
      summary: Create a new document
      description: Create a new document in the system
      operationId: createDocument
      requestBody:
        description: Document object to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
        required: true
      responses:
        '201':
          description: Document created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '400':
          description: Invalid input
  /documents/{id}:
    get:
      tags:
      - documents
      summary: Get document by ID
      description: Retrieve a specific document by its ID with line comment counts
      operationId: getDocument
      parameters:
      - name: id
        in: path
        description: Document ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: Document retrieved successfully
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/DocumentResponse'
        '404':
          description: Document not found
    put:
      tags:
      - documents
      summary: Update a document
      description: Update an existing document
      operationId: updateDocument
      parameters:
      - name: id
        in: path
        description: Document ID
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: Updated document object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '200':
          description: Document updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '404':
          description: Document not found
    delete:
      tags:
      - documents
      summary: Delete a document
      description: Delete a document by its ID
      operationId: deleteDocument
      parameters:
      - name: id
        in: path
        description: Document ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '204':
          description: Document deleted successfully
        '404':
          description: Document not found
  /documents/group/{groupId}:
    get:
      tags:
      - documents
      summary: Get documents by group
      description: Retrieve all documents belonging to a specific group
      operationId: getAllDocumentsByGroup
      parameters:
      - name: groupId
        in: path
        description: Document group ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: Group of documents retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocumentMetadataResponse'
  /documents/user/{userId}:
    get:
      tags:
      - documents
      summary: Get documents by user
      description: Retrieve all documents for a specific user
      operationId: getDocumentsByUser
      parameters:
      - name: userId
        in: path
        description: User ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: Documents retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'
  /documents/{id}/line-comments:
    get:
      tags:
      - documents
      summary: Get line comment counts
      description: Get comment counts per line for a document
      operationId: getLineCommentCounts
      parameters:
      - name: id
        in: path
        description: Document ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: Line comment counts retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  documentId:
                    type: integer
                    format: int64
                  lineCommentCounts:
                    type: object
                  additionalProperties:
                    type: integer
        '404':
          description: Document not found
  /doc-groups:
    get:
      tags:
      - doc-groups
      summary: Get all document groups
      description: Retrieve a list of all document groups
      operationId: getAllDocGroups
      responses:
        '200':
          description: List of document groups retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocGroupResponse'
    post:
      tags:
      - doc-groups
      summary: Create a new document group
      description: Create a new document group in the system
      operationId: createDocGroup
      requestBody:
        description: Document group object to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocGroupRequest'
        required: true
      responses:
        '201':
          description: Document group created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocGroupResponse'
        '400':
          description: Invalid input
  /doc-groups/{id}:
    get:
      tags:
        - doc-groups
      summary: Get document group by ID
      description: Retrieve a specific document group by its ID
      operationId: getDocGroupById
      parameters:
        - name: id
          in: path
          description: Document group ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Document group retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocGroupResponse'
        '404':
          description: Document group not found
    put:
      tags:
        - doc-groups
      summary: Update a document group
      description: Update an existing document group
      operationId: updateDocGroup
      parameters:
        - name: id
          in: path
          description: Document group ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Updated document group object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocGroupRequest'
      responses:
        '200':
          description: Document group updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocGroupResponse'
        '404':
          description: Document group not found
    delete:
      tags:
        - doc-groups
      summary: Delete a document group
      description: Delete a document group by its ID
      operationId: deleteDocGroup
      parameters:
        - name: id
          in: path
          description: Document group ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Document group deleted successfully
        '404':
          description: Document group not found
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
    Document:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        content:
          type: string
        authorId:
          type: integer
          format: int64
        groupId:
          type: integer
          format: int64
    DocumentResponse:
      allOf:
        - $ref: '#/components/schemas/Document'
        - type: object
          properties:
            lineCommentCounts:
              type: object
              additionalProperties:
                type: integer
    DocumentMetadataResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        authorId:
          type: integer
          format: int64
        groupId:
          type: integer
          format: int64
    DocGroupRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
    DocGroupResponse:
      allOf:
        - $ref: '#/components/schemas/DocGroupRequest'
        - type: object
          properties:
            id:
              type: integer
              format: int64