INSERT INTO doc_groups (name, display_name, description, icon, technology, created_at) VALUES ('react', 'React', 'A JavaScript library for building user interfaces', 'react-icon', 'Framework', CURRENT_TIMESTAMP);
INSERT INTO doc_groups (name, display_name, description, icon, technology, created_at) VALUES ('spring-boot', 'Spring Boot', 'Java framework for building production-ready applications', 'spring-icon', 'Framework', CURRENT_TIMESTAMP);
INSERT INTO doc_groups (name, display_name, description, icon, technology, created_at) VALUES ('docker', 'Docker', 'Platform for developing, shipping, and running applications in containers', 'docker-icon', 'Tool', CURRENT_TIMESTAMP);
INSERT INTO doc_groups (name, display_name, description, icon, technology, created_at) VALUES ('kubernetes', 'Kubernetes', 'Container orchestration platform for automating deployment, scaling, and management', 'k8s-icon', 'Tool', CURRENT_TIMESTAMP);
INSERT INTO doc_groups (name, display_name, description, icon, technology, created_at) VALUES ('python', 'Python', 'High-level programming language for general-purpose programming', 'python-icon', 'Language', CURRENT_TIMESTAMP);
INSERT INTO doc_groups (name, display_name, description, icon, technology, created_at) VALUES ('java', 'Java', 'Object-oriented programming language', 'java-icon', 'Language', CURRENT_TIMESTAMP);
INSERT INTO doc_groups (name, display_name, description, icon, technology, created_at) VALUES ('postgresql', 'PostgreSQL', 'Powerful open-source relational database system', 'postgres-icon', 'Database', CURRENT_TIMESTAMP);
INSERT INTO doc_groups (name, display_name, description, icon, technology, created_at) VALUES ('kafka', 'Apache Kafka', 'Distributed event streaming platform', 'kafka-icon', 'Tool', CURRENT_TIMESTAMP);
INSERT INTO documents (title, source, content, user_id, group_id, created_at, status) SELECT 'Welcome to Dockey', 'quick-start', 'Welcome to Dockey! This is your first document. Dockey is a collaborative documentation platform.', 1, id, CURRENT_TIMESTAMP, 'PUBLISHED' FROM doc_groups WHERE name = 'react';
INSERT INTO documents (title, source, content, user_id, group_id, created_at, status) SELECT 'Getting Started with React', 'react-intro', 'React is a JavaScript library for building user interfaces. Learn the basics...', 1, id, CURRENT_TIMESTAMP, 'PUBLISHED' FROM doc_groups WHERE name = 'react';
INSERT INTO documents (title, source, content, user_id, group_id, created_at, status) SELECT 'Spring Boot Quick Start', 'spring-guide', 'Spring Boot makes it easy to create stand-alone, production-grade Spring applications...', 1, id, CURRENT_TIMESTAMP, 'PUBLISHED' FROM doc_groups WHERE name = 'spring-boot';
INSERT INTO documents (title, source, content, user_id, group_id, created_at, status) SELECT 'Docker Fundamentals', 'docker-basics', 'Docker is a platform for developing, shipping, and running applications in containers...', 1, id, CURRENT_TIMESTAMP, 'PUBLISHED' FROM doc_groups WHERE name = 'docker';
INSERT INTO documents (title, source, content, user_id, group_id, created_at, status) SELECT 'Kubernetes Deployment Guide', 'k8s-deploy', 'This guide covers deploying applications on Kubernetes...', 1, id, CURRENT_TIMESTAMP, 'DRAFT' FROM doc_groups WHERE name = 'kubernetes';

